import { useState, useEffect } from 'react';

// Real views for the three birdclaw-unlocked modes. Each reads a dedicated
// /api/birdclaw/* endpoint that talks to ~/.birdclaw/birdclaw.sqlite.
const TITLES = {
  likes:   { icon: '❤️', title: 'Liked Tweets', sub: 'Tweets you have liked, pulled from birdclaw' },
  inbox:   { icon: '📬', title: 'Inbox Triage', sub: 'Mentions ranked by birdclaw’s AI scores' },
  digests: { icon: '📰', title: 'AI Digests',   sub: 'Generated by birdclaw’s digest engine' },
};

function Avatar({ url, handle }) {
  return (
    <div className="bc-avatar">
      {url ? <img src={url} alt="" loading="lazy" onError={e => (e.target.style.display = 'none')} />
           : <span>{(handle || '?')[0]?.toUpperCase()}</span>}
    </div>
  );
}

function TweetRow({ b, badge }) {
  return (
    <div className="bc-row">
      <Avatar url={b.authorProfileImageUrl} handle={b.authorHandle} />
      <div className="bc-row-body">
        <div className="bc-row-head">
          <span className="bc-name">{b.authorName || b.authorHandle}</span>
          {b.authorHandle && <span className="bc-handle">@{b.authorHandle}</span>}
          {badge != null && <span className="bc-score">{badge}</span>}
        </div>
        <div className="bc-text">{b.text}</div>
        {b.summary && <div className="bc-summary">{b.summary}</div>}
        <div className="bc-meta">
          {b.likeCount != null && <span>❤ {b.likeCount}</span>}
          {b.url && <a href={b.url} target="_blank" rel="noopener noreferrer">open ↗</a>}
        </div>
      </div>
    </div>
  );
}

export default function BirdclawPanel({ mode, onClose }) {
  const meta = TITLES[mode] || { icon: '✨', title: mode, sub: '' };
  const [state, setState] = useState({ loading: true, items: [], text: '', err: '', needsCli: false });
  const [period, setPeriod] = useState('today');

  useEffect(() => {
    let alive = true;
    setState(s => ({ ...s, loading: true, err: '' }));
    const url = mode === 'digests' ? `/api/birdclaw/digest?period=${period}` : `/api/birdclaw/${mode}`;
    fetch(url)
      .then(r => r.json())
      .then(d => { if (!alive) return;
        setState({ loading: false, items: d.items || [], text: d.text || '', err: d.ok ? '' : (d.msg || 'Failed'), needsCli: !!d.needsCli });
      })
      .catch(e => alive && setState({ loading: false, items: [], text: '', err: String(e), needsCli: false }));
    return () => { alive = false; };
  }, [mode, period]);

  return (
    <div className="bc-panel">
      <div className="bc-header">
        <div>
          <h2 className="bc-title">{meta.icon} {meta.title}</h2>
          <div className="bc-sub">{meta.sub}</div>
        </div>
        <button className="bc-close" onClick={onClose} aria-label="Close">✕</button>
      </div>

      {mode === 'digests' && (
        <div className="bc-tabs">
          {['today', 'week'].map(p => (
            <button key={p} className={`bc-tab ${period === p ? 'active' : ''}`} onClick={() => setPeriod(p)}>
              {p === 'today' ? 'Today' : 'This week'}
            </button>
          ))}
        </div>
      )}

      {state.loading && <div className="bc-state">Loading…</div>}

      {!state.loading && state.err && (
        <div className="bc-state bc-error">
          <div>{state.err}</div>
          {state.needsCli && <div className="bc-hint">Install birdclaw (Node ≥25) and run <code>birdclaw init</code> to enable this.</div>}
        </div>
      )}

      {!state.loading && !state.err && mode === 'digests' && (
        <pre className="bc-digest">{state.text || 'No digest content.'}</pre>
      )}

      {!state.loading && !state.err && mode !== 'digests' && (
        state.items.length === 0
          ? <div className="bc-state">Nothing here yet. Sync birdclaw to populate {meta.title.toLowerCase()}.</div>
          : <div className="bc-list">
              {state.items.map(b => (
                <TweetRow key={b.id} b={b} badge={mode === 'inbox' ? b.score : null} />
              ))}
            </div>
      )}
    </div>
  );
}
